# Note: This file is not reloaded automatically.

# Site settings
title: CdMHS TEC Club
email: your-email@domain.com
description: >
  Technology. Entrepreneurship. Coding.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tec-club.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
paginate_path: "/page/:num/"
permalink: pretty
name: CdMHS TEC Club
accent_color: "#FFC107" # to be implemented

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-mentions
  - jemoji